### ISSUE TITLE
Issue to download the credit-api jarfile

### ISSUE THREAD

**Issue by myriam97** [eliasnogueira/credit-api#54]
**Describe the issue**
I try to do the exercise "Automating API tests with Rest-Assured" but I can't download the credit-api-1.4.8.jar file (the latest version). 

**Steps**
1. Go to the 'terminal'
2. Execute the following command 'java -jar credit-api-1.4.8.jar'
3. See the error

**Expected behaviour**
After these three steps, I see this error message : 'error : Unable to access jarfile credit-api-1.4.8.jar'

**Additional information**
With this, I can't continue the exercise.

**Comment by eliasnogueira** [comment]
Hi @myriam97,
Would you mind double-checking if you have the `credit-api-1.4.8.jar` file in the same folder you ran the command?

![execution](https://user-images.. ithubusercontent.com/284888/151708162-9513327c-8a71-4f7b-ac89-4d5328194ebe.png)

In the screenshot above you can see I've listed the `jar` files in my Download folder, and the `credit-api-1.4.8.jar` is there.
In item 2 you can see the application starting.
